project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Analysis of Global Health Expenditure"
  author:
    - Justin Mathew (JTM2223)
    - Aditiya Vurukala (AV3244)
  repo-url: https://github.com/jtm2223/Global-Health-Expenditure
  date: November 18, 2024
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


