# Conclusion
Through the project, we explored the American housing data in depth to get
a better grasp of the housing market. Our goal was to discover some trends or 
ideas that we previously did not know as both of us begin to move into the point 
of our lives where we look for our own places. Through our analysis we did 
manage to discover new ones while also discovering some we didn't know. For 
example, we discovered how the data supported the idea that fewer houses were 
being built. In addition, we found data that supported the trend of
fewer houses being built. Another surprising thing we found was that the
Washington D.C. actually had more units that were being rented than there are
units where the owner lives in it. This analysis we found especially surprising
as we did not see the states with big cities show up on the list. Our analysis
also led us to prove ideas we had already such as the fact that the northeast
and west were more expensive housing markets or that there were many more 
single houses than other forms of houses like town homes or apartments. While
creating the interactive graph we discovered how important big cities were in
the overall median unit value in a state and also were reaffirmed on which
states had the highest median unit value. However, though we discovered all of 
this, the applicability may not be the best as the data was gathered from 
2016-2020. Though this data is fairly recent, with major events like the 
pandemic, a lot has changed, especially in the housing market. For example, 
since 2023, there has actually been an uptick in new houses being built 
which was not what our graph showed. Another issue was that some of the columns 
in the data lacked clear context and were not able to be utilized for deeper 
insights. In addition, due to the set up and structure of the data we could not 
explore certain things we wanted to like rent distribution based on number of 
bedrooms and more. Many of the columns in the dataset displayed the same 
information but slightly tweaked which prevented us from having more complex 
analysis. Going forward for future research we could include integrating more of
a dynamically growing data set and more outside social economic data. This is so
we are not just assuming from inference but actual data when explaining trends 
that are found. Overall, we learned about just how volatile and complicated the 
housing market really is.